export const category: { category: string; category_number: number }[] = [
  { category: "아무거나", category_number: -1 },
  { category: "일반지식", category_number: 9 },
  { category: "책", category_number: 10 },
  { category: "영화", category_number: 11 },
  { category: "음악", category_number: 12 },
  { category: "뮤지컬&연극", category_number: 13 },
  { category: "TV", category_number: 14 },
  { category: "비디오게임", category_number: 15 },
  { category: "보드게임", category_number: 16 },
  { category: "과학&자연", category_number: 17 },
  { category: "컴퓨터", category_number: 18 },
  { category: "수학", category_number: 19 },
  { category: "신화학", category_number: 20 },
  { category: "스포츠", category_number: 21 },
  { category: "지리학", category_number: 22 },
  { category: "역사", category_number: 23 },
  { category: "정치", category_number: 24 },
  { category: "예술", category_number: 25 },
  { category: "유명인사", category_number: 26 },
  { category: "동물", category_number: 27 },
];
